#Varibles
name = "chetan singh"
age = 25
price = 20.25

print("my name is", name, "and my age is", age, "and the price is", price)
print(type(name))
print(type(age))
print(type(price))

age = 30
old = False
a = None
print(type(old))
print(type(a))

a = 20
b = 100
print(a + b)

#arithmetic operators
x = 10
y = 5
print(x + y)  # Addition
print(x - y)  # Subtraction
print(x * y)  # Multiplication
print(x / y)  # Division
print(x % y)  # Modulus
print(x ** y) # Exponentiation
print(x // y) # Floor Division
#relational operators
a = 50
b = 20
print(a == b)  # Equal to
print(a != b)  # Not equal to
print(a > b)   # Greater than
print(a < b)   # Less than
print(a >= b)  # Greater than or equal to
print(a <= b)  # Less than or equal to
#assignment operators
num = 10
num = num + 10
print("num : ", num)
#logical operators
a = 50
b = 30
print(not False)  # Logical NOT
print(not (a > b))  # Logical NOT

val1 = False
val2 = False
print("and operation : ", val1 and val2)  # Logical AND
print("or operator:", (a == b) or (a > b))  # Logical OR
name = input("enter your name : ")
print("hello", name)
Name = input("enter your name : ")
Age = input("enter your age : ")
mark = input("enter your mark : ")

print("welcame", name)
print("your age is", Age)
print("your mark is", mark)

A = int(input("enter a number : "))
B = int(input("enter a number : "))
print("the sum is : ", A + B)




